"1": "Alberta Government Library"
"2": "Alberta Government Library"
"3": "NorQuest College"
"4": "Alberta Health Services"
"5": "NorQuest College"
"6": "Alberta Health Services"
"7": "Alberta Health Services"
"8": "Keyano College"
"9": "Alberta Health Services"
"10": "Alberta Health Services"
"11": "Alberta Innovates"
"12": "Alberta Innovates"
"13": "NEOS Free Internet Resources"
"14": "Alberta Innovates"
"15": "Alberta Innovates"
"16": "University of Alberta"
"17": "Covenant Health"
"18": "Covenant Health"
"19": "Alberta Health Services"
"20": "Alberta Health Services"
"21": "Concordia University of Edmonton"
"22": "Alberta Health Services"
"23": "Burman University"
"24": "MacEwan University"
"25": "Alberta Health Services"
"26": "Alberta Health Services"
"27": "Alberta Health Services"
"28": "Grande Prairie Regional College"
"29": "MacEwan University"
"30": "Alberta Health Services"
"31": "King's University"
"32": "Newman Theological College"
"33": "Olds College"
"34": "Concordia Lutheran Seminary"
"35": "Red Deer College"
"36": "Vanguard College"
"37": "University of Alberta"
"38": "University of Alberta"
"39": "University of Alberta"
"40": "University of Alberta"
"41": "University of Alberta"
"42": "University of Alberta"
"43": "University of Alberta"
"44": "University of Alberta"
"45": "University of Alberta"
"46": "University of Alberta"
"47": "Alberta Health Services"
"48": "University of Alberta"
"49": "University of Alberta"
"50": "University of Alberta"
"51": "University of Alberta"
"52": "Lakeland College"
"53": "Lakeland College"
"54": "Grande Prairie Regional College"
"55": "MacEwan University"
"56": "MacEwan University"
"57": "MacEwan University"
"58": "Alberta Health Services"
"59": "Vanguard College"
"60": "Grande Prairie Regional College"
"61": "Lakeland College"
