aegeo:  
  name: "Alberta Geological Survey"
  locationurl: "http://ags.aer.ca/about-the-ags/contact-us.htm"
aginternet:  
  name: "Alberta Government Library - Internet"
  locationurl: "https://www.servicealberta.ca/alberta-government-library.cfm"
aglcap:  
  name: "Alberta Government Library"
  locationurl: "https://www.servicealberta.ca/alberta-government-library.cfm"
ahsah:  
  name: "Alberta Health Services - Alberta Hospital Edmonton"
  locationurl: 
ahsahe:  
  name: "Alberta Health Services - Alberta Hospital Edmonton"
  locationurl: 
ahscenten:  
  name: "Alberta Health Services - Centennial Centre"
  locationurl: 
ahserc:  
  name: "Alberta Health Services - Education Resource Centre"
  locationurl: 
ahsmhrh:  
  name: "Alberta Health Services - Medicine Hat Regional Hospital"
  locationurl: 
ahsqeii:  
  name: "Alberta Health Services - Queen Elizabeth II Hospital"
  locationurl: 
ahsrah:  
  name: "Alberta Health Services - Royal Alexandra Hospital"
  locationurl: 
ahsreddr:  
  name: "Alberta Health Services - Red Deer Regional Hospital"
  locationurl: "https://krs.libguides.com/aboutus/rdrh"
ahssturg:  
  name: "Alberta Health Services - SturgeonIn TransitionExpect Delays"
  locationurl: 
ahsplc:  
  name: "Alberta Health Services - Peter Lougheed Centre"
  locationurl: 
ahsrvgh:  
  name: "Alberta Health Services - Rockyview General Hospital"
  locationurl: "https://krs.libguides.com/aboutus/rgh"
ahstbcc:  
  name: "Alberta Health Services - Tom Baker Cancer Centre"
  locationurl: 
ahswhc:  
  name: "Alberta Health Services - Women's Health Centre Alberta Children's Hospital"
  locationurl: 
ahsach:  
  name: "Alberta Health Services - Alberta Children's Hospital"
  locationurl: 
ahsctr15:   
  name: "Alberta Health Services - Centre 15"
  locationurl: 
ahsctr:   
  name: "Alberta Health Services - Centre 15"
  locationurl: 
15:   
  name: "Alberta Health Services - Centre 15"
  locationurl: 
ahscross:   
  name: "Alberta Health Services - Cross Cancer Institute"
  locationurl: 
ahsint:   
  name: "Alberta Health Services - Internet"
  locationurl: "https://krs.libguides.com/home"
ahskec:   
  name: "Alberta Health Services - Kaye Edmonton Clinic"
  locationurl: "https://krs.libguides.com/aboutus/kec"
ahsglenrse:   
  name: "Alberta Health Services - Glenrose Rehabilitation Hospital"
  locationurl: "https://krs.libguides.com/aboutus/grh"
ahsglenrs:   
  name: "Alberta Health Services - Glenrose Rehabilitation Hospital"
  locationurl: "https://krs.libguides.com/aboutus/grh"
aitfcalg:   
  name: "Alberta Innovates - Calgary"
  locationurl: 
aitfc-fer:   
  name: "Alberta Innovates - CFer Technologies"
  locationurl: "​https://www.neoslibraries.ca/member-libraries/alberta-innovates/c-fer-library"
aitfcfer:   
  name: "Alberta Innovates - CFer Technologies"
  locationurl: "​https://www.neoslibraries.ca/member-libraries/alberta-innovates/c-fer-library"
aitfmw:   
  name: "Alberta Innovates - Mill Woods"
  locationurl: "​https://www.neoslibraries.ca/member-libraries/alberta-innovates/mill-woods-library/​"
aitfveg:   
  name: "Alberta Innovates - Vegreville"
  locationurl: 
aitfdevon:   
  name: "Alberta Innovates - Devon"
  locationurl: 
concordia:   
  name: "Concordia University of Edmonton"  
  locationurl: "http://library.concordia.ab.ca"
concordsem:   
  name: "Concordia Lutheran Seminary"
  locationurl: "​http://www.concordiasem.ab.ca/research/library_information.php​"
covenantgn: 
  name: "Covenant Health - Grey Nuns Community Hospital"
  locationurl: ​"https://www.covenanthealth.ca/corporate-information/library-services"
covenantmh:   
  name: "Covenant Health - Misericordia Community Hospital"
  locationurl: "​https://www.covenanthealth.ca/corporate-information/library-services​"
cross:   
  name: "Alberta Health Services - Cross Cancer Institute"
  locationurl: 
cuc:   
  name: "Burman University"
  locationurl: "https://www.burmanu.ca/library"
burman:   
  name: "Burman University"
  locationurl: "https://www.burmanu.ca/library"
gprc:   
  name: "Grande Prairie Regional College"
  locationurl: "https://www.gprc.ab.ca/library"
gprcfrvw:   
  name: "Grande Prairie Regional College - Fairview"
  locationurl: "https://www.gprc.ab.ca/library"
gprcgp:   
  name: "Grande Prairie Regional College - Grande Prairie"
  locationurl: "https://www.gprc.ab.ca/library"
gprcint:   
  name: "Grande Prairie Regional College - Internet"
  locationurl: "https://www.gprc.ab.ca/library"
grmacacc:   
  name: "MacEwan University - Alberta College Campus"
  locationurl: "https://library.macewan.ca/"
grmaccac:   
  name: "MacEwan University - Centre for Arts & Communications"
  locationurl: "https://library.macewan.ca/"
grmacint:   
  name: "MacEwan University - Internet"
  locationurl: "https://library.macewan.ca/"
grmacsoc:   
  name: "MacEwan University - South CampusOn the MoveExpect Delay"
  locationurl: "https://library.macewan.ca/​"
grmactsv:   
  name: "MacEwan University - Technical Services"
  locationurl: "https://library.macewan.ca/"
grmacewan:   
  name: "MacEwan University - City Centre Campus"
  locationurl: "https://library.macewan.ca/"
justiceca:   
  name: "Justice Canada"
  locationurl: 
keyano:   
  name: "Keyano College"
  locationurl: "http://www.keyano.ca/Services/Library​"
king:   
  name: "The King's University"
  locationurl: "https://www.kingsu.ca/library"
kings:   
  name: "The King's University"  
  locationurl: "https://www.kingsu.ca/library"
lakelndl:   
  name: "Lakeland College - Lloydminster"
  locationurl: "https://www.neoslibraries.ca/member-libraries/lakeland/lloydminster-campus-library/"
lakelndll:   
  name: "Lakeland College - Lloydminster"
  locationurl: "https://www.neoslibraries.ca/member-libraries/lakeland/lloydminster-campus-library/"
lakelndin:   
  name: "Lakeland College - Internet"
  locationurl: "​​https://web.lakelandcollege.ca/commons/library/​"
lakelndvr:   
  name: "Lakeland College - Vermilion"
  locationurl: "https://www.neoslibraries.ca/member-libraries/lakeland/vermilion-campus-library/​"
neosfree:   
  name: "NEOS Free Internet Resources"
  locationurl: 
neosfre:   
  name: "NEOS Free Internet Resources"
  locationurl: 
newman:   
  name: "Newman Theological College"
  locationurl: "https://www.newman.edu/Library"
norqmain:   
  name: "NorQuest College - Main Building"
  locationurl: "https://library.norquest.ca"
norqwest:   
  name: "NorQuest College - Westmount"
  locationurl: "​https://library.norquest.ca"
old:   
  name: "Olds College"
  locationurl: "​https://www.oldscollege.ca/student-life/learning-commons/index.html​"
olds:   
  name: "Olds College"
  locationurl: "https://www.oldscollege.ca/student-life/learning-commons/index.html"
reddeerc:   
  name: "Red Deer College"
  locationurl: "https://rdc.ab.ca/current-students/library"
reddeer:   
  name: "Red Deer College"
  locationurl: "https://rdc.ab.ca/current-students/library"
taylor:   
  name: "Vanguard College - Taylor"
  locationurl: "http://www.taylor-edu.ca/seminary/library"
uaarchiv:   
  name: "University of Alberta - Archives"
  locationurl: "https://www.library.ualberta.ca/locations/archives"
uaarchives:   
  name: "University of Alberta - Archives"
  locationurl: "https://www.library.ualberta.ca/locations/archives"
uaaug:   
  name: "University of Alberta - Augustana"
  locationurl: "https://www.library.ualberta.ca/locations/augustana"
uarcrf:   
  name: "University of Alberta - Research and Collections Resource Facility"
  locationurl: "https://www.library.ualberta.ca/locations/rcrf"
uabsj:   
  name: "University of Alberta - Bibliothèque Saint-Jean"
  locationurl: "https://www.library.ualberta.ca/locations/bsj"
uabusi:   
  name: "University of Alberta - Winspear Business"
  locationurl: "https://www.library.ualberta.ca/locations/winspear"
uabusiness:   
  name: "University of Alberta - Winspear Business"
  locationurl: "https://www.library.ualberta.ca/locations/winspear"
uaeduc:   
  name: "University of Alberta - HT Coutts Education"
  locationurl: "https://www.library.ualberta.ca/locations/coutts"
uahlthsc:   
  name: "University of Alberta JW Scott Health Sciences"
  locationurl: "https://www.library.ualberta.ca/locations/scott"
uahss:   
  name: "University of Alberta - Rutherford Humanities & Social Science"
  locationurl: "https://www.library.ualberta.ca/locations/rutherford"
uainternet:   
  name: "University of Alberta - Internet"
  locationurl: "https://www.library.ualberta.ca/services/off-campus-access"
ualaw:   
  name: "University of Alberta - JA Weir Law"
  locationurl: "https://www.library.ualberta.ca/locations/law"
uamath:   
  name: "University of Alberta - Cameron Mathematics"
  locationurl: "https://www.library.ualberta.ca/locations/cameron"
uascitech:   
  name: "University of Alberta - Cameron Science & Technology"
  locationurl: "https://www.library.ualberta.ca/locations/cameron"
uasjc:   
  name: "University of Alberta - St Joseph's College"
  locationurl: "https://www.library.ualberta.ca/locations/stjosephs"
uaspcol:   
  name: "University of Alberta - Bruce Peel Special Collections"
  locationurl: "https://www.library.ualberta.ca/locations/bpsc"
uaspcoll:   
  name: "University of Alberta - Bruce Peel Special Collections"
  locationurl: "https://www.library.ualberta.ca/locations/bpsc"
uatechserv:   
  name: "University of Alberta - Bibliographic Services"
  locationurl: 
vanguard:   
  name: "Vanguard College"
  locationurl: "http://www.vanguardcollege.com/library"
nlcgr:   
  name: "Northern Lakes College - Grouard"
  locationurl: "https://www.northernlakescollege.ca/current-students/library-services"
nlcint:  
  name: "Northern Lakes College - Internet"
  locationurl: "https://www.northernlakescollege.ca/current-students/library-services"
nlcsl:   
  name: "Northern Lakes College - Slave Lake"  
  locationurl: "https://www.northernlakescollege.ca/current-students/library-services"
